// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT8X3qHKshUMVpJbjrpa8AczmBJLqi1HI',
    appId: '1:530526592725:web:a930b17a8852cd09794c5c',
    messagingSenderId: '530526592725',
    projectId: 'ngajiii',
    authDomain: 'ngajiii.firebaseapp.com',
    storageBucket: 'ngajiii.firebasestorage.app',
    measurementId: 'G-WMEE92F8D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApy8I60_Txs1aGbX9fLQIavOVh-JqZ0pM',
    appId: '1:530526592725:android:ae67aa52cc19b636794c5c',
    messagingSenderId: '530526592725',
    projectId: 'ngajiii',
    storageBucket: 'ngajiii.firebasestorage.app',
  );

}